"""Physical sampling and leave-one-modality-out batch planning."""

from .geometry import (
    V0_SLAB_GEOMETRY,
    AxisAlignedSlab,
    Coordinate3D,
    NonOverlappingSelectionError,
    SlabGeometry,
    are_pairwise_non_overlapping,
    select_non_overlapping_centers,
    select_non_overlapping_indices,
    slabs_intersect,
)
from .modality_completion import (
    ALL_MODALITY_IDS,
    BRATS_MODALITIES,
    CandidatePosition,
    CompletionLocationPlan,
    ModalityCompletionBatchPlan,
    ModalityCompletionPlanningError,
    PatchKey,
    PatchMetadata,
    PatchRole,
    plan_modality_completion_batch,
)
from .records import (
    PATCH_PLAN_SCHEMA,
    PATCH_PLAN_SCHEMA_VERSION,
    GeometryRecord,
    MaterializedPatchPlan,
    PatchIdentity,
    PatchPlanError,
    PatchPlanRecord,
    PlanCaseIdentity,
    canonical_json_bytes,
    canonical_sha256,
    load_patch_plan,
    save_patch_plan,
)

__all__ = [
    "ALL_MODALITY_IDS",
    "BRATS_MODALITIES",
    "AxisAlignedSlab",
    "CandidatePosition",
    "CompletionLocationPlan",
    "Coordinate3D",
    "ModalityCompletionBatchPlan",
    "ModalityCompletionPlanningError",
    "NonOverlappingSelectionError",
    "PatchKey",
    "PatchIdentity",
    "PatchMetadata",
    "PatchPlanError",
    "PatchPlanRecord",
    "PatchRole",
    "PATCH_PLAN_SCHEMA",
    "PATCH_PLAN_SCHEMA_VERSION",
    "PlanCaseIdentity",
    "SlabGeometry",
    "V0_SLAB_GEOMETRY",
    "are_pairwise_non_overlapping",
    "canonical_json_bytes",
    "canonical_sha256",
    "GeometryRecord",
    "load_patch_plan",
    "MaterializedPatchPlan",
    "plan_modality_completion_batch",
    "save_patch_plan",
    "select_non_overlapping_centers",
    "select_non_overlapping_indices",
    "slabs_intersect",
]
